name: GraphQL Inspector
on: [push]

jobs:
  graphql-inspector:
    name: Trigger GraphQL Inspector
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - uses: kamilkisiela/graphql-inspector@v2.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'main'
          schema: 'graphql/schema.graphql'
