name: GraphQL Inspector

on: [push]

jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./graphql
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: kamilkisiela/graphql-inspector@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          schema: 'master:schema.graphql'