version: 2

name: GraphQL Inspector
on:
  push:
    branches-ignore: 
      - master
defaults:
  run:
    working-directory: graphql

jobs:
  build:
    docker:
      image: kamilkisiela/graphql-inspector
    steps:
      - checkout
      - run: 
          name: graphql-inspector
          command: 'graphql-inspector diff "git:origin/master:./schema.graphql" "schema.graphql"'
