version: 2

name: Laravel Workflows
on: push

jobs:
  build:
    name: Laravel/GraphQl Build
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/composer
      - uses: ./.github/actions/config-laravel
      - run: ./vendor/bin/phpunit
      - run: ./vendor/bin/phpcs
      # - run: |
      #     cd ~
      #     find -name schema.graphql
      # - name: GraphQl Inspector
      #   uses: kamilkisiela/graphql-inspector@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     schema: 'graphql:schema.graphql'
      #     annotations: true
  