name: Laravel Workflow
on: push

jobs:
  build:
    name: Laravel/GraphQl Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/composer
      - run: ./vendor/bin/PHPUnit
      - run: ./vendor/bin/phpcs