name: Laravel Workflows
on: push

defaults:
  run:
    working-directory: ./graphql 

jobs:
  build:
    name: Laravel/GraphQl Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/composer
      - uses: ./.github/actions/config-laravel
      - run: ./vendor/bin/phpunit
      - run: ./vendor/bin/phpcs
      - uses: kamilkisiela/graphql-inspector@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          schema: 'main:schema.graphql'
  