name: Laravel Workflow
on: [push, pull_request]

jobs:
  build:
    name: Laravel
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/composer
      - uses: ./.github/actions/config-laravel
      - run: ./vendor/bin/phpunit
      - run: ./vendor/bin/phpcs
      - run: ./vendor/bin/phpstan analyse --memory-limit=2G
