name: Laravel Workflow
on: [push, pull_request]

jobs:
  build:
    name: Laravel/GraphQl Build
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/composer
      - uses: ./.github/actions/config-laravel
      - run: ./vendor/bin/phpunit
      - run: ./vendor/bin/phpcs
      - name: graphql-inspector
        uses: kamilkisiela/graphql-inspector@v2.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          schema: 'main:graphql/schema.graphql'
  